APP_NAME = "YamYamPick"
SCHEME = "YamYamPick"
BUNDLE_ID = "com.Pepsi-Club.YamYamPick"

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]

default_platform(:ios)

platform :ios do
  desc "Download Ignored"
  lane :getig do |options|
    Dir.chdir("../") do
      github_access_token = sh("git config --global user.password")
      sh("make download-privates token=#{github_access_token}")
    end
  end

  desc "Set Project"
  lane :setpj do |options|
    Dir.chdir("../") do
      sh("tuist clean")
      sh("tuist fetch")
      sh("tuist generate")
      match(
        type: "development",
        readonly: true,
        app_identifier: BUNDLE_ID,
        git_url: ENV["MATCH_URL"]
      )
      match(
        type: "appstore",
        readonly: true,
        app_identifier: BUNDLE_ID,
        git_url: ENV["MATCH_URL"]
      )
    end
  end

  desc "Push to TestFlight"
  lane :tf do |options|
    match(
      type: "appstore",
      readonly: true
    )

    app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_content: ENV['APP_STORE_PRIVATE_KEY'],
      is_key_content_base64: true, 
      in_house: false
    )
    
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
      export_method: "app-store"
    )

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end